export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const REMOVE_ALL_ITEMS_ON_ORDER = "REMOVE_ALL_ITEMS_ON_ORDER";
